"""drop system_prompt and updated_at from chat_history

Revision ID: 11932e9557d2
Revises: c1e9dfe789a3
Create Date: 2026-06-02 18:33:03.622134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11932e9557d2'
down_revision: Union[str, Sequence[str], None] = 'c1e9dfe789a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'system_prompt')
    op.create_index(op.f('ix_episodes_session_id'), 'episodes', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_session_id'), table_name='episodes')
    op.add_column('chat_history', sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
