"""add session_id to episodes and remove ep_ids from chat_history

Revision ID: 7018e01ea217
Revises: b039435c6fa2
Create Date: 2026-06-02 14:59:44.597791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7018e01ea217'
down_revision: Union[str, Sequence[str], None] = 'b039435c6fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'ep_ids')
    op.add_column('episodes', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'episodes', 'chat_history', ['session_id'], ['session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'episodes', type_='foreignkey')
    op.drop_column('episodes', 'session_id')
    op.add_column('chat_history', sa.Column('ep_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
