"""rename ep_id and add ep_ids to chat_history

Revision ID: b039435c6fa2
Revises: cad0acd9bab1
Create Date: 2026-06-02 14:57:15.798860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b039435c6fa2'
down_revision: Union[str, Sequence[str], None] = 'cad0acd9bab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('active_ep_id', sa.UUID(), nullable=True))
    op.add_column('chat_history', sa.Column('ep_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.drop_constraint(op.f('chat_history_ep_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'episodes', ['active_ep_id'], ['id'])
    op.drop_column('chat_history', 'ep_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('ep_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_ep_id_fkey'), 'chat_history', 'episodes', ['ep_id'], ['id'])
    op.drop_column('chat_history', 'ep_ids')
    op.drop_column('chat_history', 'active_ep_id')
    # ### end Alembic commands ###
