"""drop active_ep_id from chat_history

Revision ID: b2a7d9579673
Revises: 7018e01ea217
Create Date: 2026-06-02 15:10:01.177023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a7d9579673'
down_revision: Union[str, Sequence[str], None] = '7018e01ea217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_history_active_ep_id_fkey'), 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'active_ep_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('active_ep_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_history_active_ep_id_fkey'), 'chat_history', 'episodes', ['active_ep_id'], ['id'])
    # ### end Alembic commands ###
