"""add memory tables

Revision ID: cad0acd9bab1
Revises: 4609f8a7d66b
Create Date: 2026-06-02 14:47:59.031769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cad0acd9bab1'
down_revision: Union[str, Sequence[str], None] = '4609f8a7d66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dreams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dream_type', sa.Enum('pattern', 'contradiction', 'insight', 'hypothesis', 'emotional', name='dreamtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('source_episode_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('related_entity_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('dreamed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reinforced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_taxonomy',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['entity_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', 'summarized', 'dreamed', name='episodestatus'), server_default='active', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('importance_score', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clarifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context_rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'asked', 'resolved', 'dismissed', name='clarificationstatus'), server_default='pending', nullable=False),
    sa.Column('priority_score', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source_dream_id', sa.UUID(), nullable=True),
    sa.Column('source_episode_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_dream_id'], ['dreams.id'], ),
    sa.ForeignKeyConstraint(['source_episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_type'], ['entity_taxonomy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entities_name'), 'memory_entities', ['name'], unique=False)
    op.create_table('memory_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_episode_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.ForeignKeyConstraint(['source_episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['memory_entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['memory_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_relations_relation_type'), 'memory_relations', ['relation_type'], unique=False)
    op.add_column('chat_history', sa.Column('ep_id', sa.UUID(), nullable=True))
    op.alter_column('chat_history', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'chat_history', 'episodes', ['ep_id'], ['id'])
    op.drop_column('chat_history', 'schema_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('schema_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.alter_column('chat_history', 'system_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('chat_history', 'ep_id')
    op.drop_index(op.f('ix_memory_relations_relation_type'), table_name='memory_relations')
    op.drop_table('memory_relations')
    op.drop_index(op.f('ix_memory_entities_name'), table_name='memory_entities')
    op.drop_table('memory_entities')
    op.drop_table('clarifications')
    op.drop_table('episodes')
    op.drop_table('entity_taxonomy')
    op.drop_table('dreams')
    # ### end Alembic commands ###
