"""replace_memory_relation_with_predicates_and_facts

Revision ID: f419011736ce
Revises: 11932e9557d2
Create Date: 2026-06-06 15:15:55.952522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f419011736ce'
down_revision: Union[str, Sequence[str], None] = '11932e9557d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predicates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('predicate_id', sa.UUID(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('source_episode_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['memory_entities.id'], ),
    sa.ForeignKeyConstraint(['predicate_id'], ['predicates.id'], ),
    sa.ForeignKeyConstraint(['source_episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['memory_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_memory_relations_relation_type'), table_name='memory_relations')
    op.drop_table('memory_relations')
    op.drop_column('memory_entities', 'attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_entities', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.create_table('memory_relations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_episode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.5'::double precision"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_episode_id'], ['episodes.id'], name=op.f('memory_relations_source_episode_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['memory_entities.id'], name=op.f('memory_relations_source_id_fkey')),
    sa.ForeignKeyConstraint(['target_id'], ['memory_entities.id'], name=op.f('memory_relations_target_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memory_relations_pkey'))
    )
    op.create_index(op.f('ix_memory_relations_relation_type'), 'memory_relations', ['relation_type'], unique=False)
    op.drop_table('entity_facts')
    op.drop_table('predicates')
    # ### end Alembic commands ###
